# Generated by Django 4.2.18 on 2025-07-24 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_leetcodedata_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leetcodedata',
            name='last_updated',
        ),
        migrations.AddField(
            model_name='leetcodedata',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leetcodedata',
            name='top_percentage',
            field=models.FloatField(default=0.0),
        ),
    ]
