# Generated by Django 4.2.23 on 2025-07-24 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_leetcodedata_last_updated_leetcodedata_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leetcodedata',
            name='rating',
            field=models.CharField(default='--', max_length=100),
        ),
        migrations.AlterField(
            model_name='leetcodedata',
            name='top_percentage',
            field=models.CharField(default='--', max_length=100),
        ),
    ]
