# Generated by Django 4.2.18 on 2025-07-24 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_leetcodedata_delete_leetcodeprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='leetcodedata',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
